#FROM openjdk:1.8
#EXPOSE 8080
#ADD target/Employee_db-0.0.1-SNAPSHOT.jar Employee_db-0.0.1-SNAPSHOT.jar
#ENTRYPOINT ["java","-jar","Employee_db-0.0.1-SNAPSHOT.jar"]
 
FROM maven:3.6.0-jdk-1.8-slim AS build
COPY pom.xml /Employee_db/
COPY src /Employee_db/src
RUN mvn -f /Employee_db/pom.xml clean package

# Run stage
FROM openjdk:1.8-jdk-alpine
EXPOSE 8080
COPY --from=build /app/target/Employee_db-0.0.1-SNAPSHOT.jar /Employee_db/Employee_db-0.0.1-SNAPSHOT.jar
ADD target/Employee_db-0.0.1-SNAPSHOT.jar Employee_db-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app/app.jar"]